const generos = [];
const peliculasNl = [];
const peliculasCls = [];
let peliculas = [];
let genero;
let peliculaIndividual;
let pelicula;
let canastaDeCompra = 0;
let canastaFinal = 0;
let textoConfirmacion = 'Sus peliculas son: ';